### ISSUE TITLE
An error!

### ISSUE THREAD

**Issue by KarlKnopf** [NathanSalapat/Survival_game#1]
When following your tutorial, I downloaded Survival_game, but when I tried to load it up I got this error: 
ModError: Failed to load and run script from D:\minetest-5.8.0-win64\bin\..\games\Survival_game\mods\doors\init.lua:
D:\minetest-5.8.0-win64\bin\..\builtin\game\register.lua:200: bad argument #5 to 'register_item_raw' (table expected, got string)
stack traceback:
	[C]: in function 'register_item_raw'
	D:\minetest-5.8.0-win64\bin\..\builtin\game\register.lua:200: in function 'register_item'
	D:\minetest-5.8.0-win64\bin\..\builtin\game\register.lua:226: in function 'register_node'
	...8.0-win64\bin\..\games\Survival_game\mods\doors\init.lua:749: in function 'register_fencegate'
	...8.0-win64\bin\..\games\Survival_game\mods\doors\init.lua:761: in main chunk
Check debug.txt for details.

I can't seem to find anything wrong with the code, so I am hoping you could help me please.

**Comment by NathanSalapat** [comment]
Sorry I no longer maintain this code. The error is due to engine changes. I had to fix it once before for another mod, I believe it had something to do with stair registrations, but I could be wrong.

**Comment by KarlKnopf** [comment]
Would I still be able to follow the tutorial without it?

**Comment by NathanSalapat** [comment]
I'll be honest, I don't know what tutorials you are talking about. This is quite old code, and the tutorials would be just as old.

**Comment by KarlKnopf** [comment]
Okay. Thank you anyway.
